保存先をdbにする firstcommit
n-ikeda-being/fjord_bootcamp_memoapp pull request #4
Opened 2022-11-08 07:10 UTC by n-ikeda-being

2022-11-13 15:36 UTC, u1tnk requested changes

2022-11-13 15:36 UTC, u1tnk commented on memo.rb
> +  def write(new_id, title, content)
updateがSQLと合わせているのでこちらも insertの方が良いと思います。
writeだとinsertでもupdateでも使えそうな名前という事もあります。

2022-11-13 15:36 UTC, u1tnk commented on memo.rb
> +  new_id = (id.max + 1)
DBには insert時に自動でidを作成してくれる機能があるのでそちらを使いましょう。

この処理だと、今後この処理を実行するサーバが複数になったときに同時に来たリクエストに同じIDを生成してしまってエラーになります。DBでのID採番は便利というだけでなくこういう問題への対処でもあります。

2022-11-14 02:13 UTC, n-ikeda-being commented on memo.rb
> +  def write(new_id, title, content)
たしかにそうですね🙇‍♀️修正しました。

2022-11-14 05:05 UTC, n-ikeda-being commented on memo.rb
> +  new_id = (id.max + 1)
修正しました。

2022-11-14 14:44 UTC, u1tnk approved these changes

2022-11-14 23:59 UTC, merged